"""
Executor
- the deterministic ground truth of the system

WHAT THIS IS
- A function that takes target code + test code, runs the test inside
  a Docker container, and returns pass/fail

WHY IT MATTERS
- LLMs lie, they will tell you a test "passes" when it doesn't
- `pytest` does not lie
- introduces deterministic verification into the pipeline
"""

import subprocess
import tempfile
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class ExecutorResult:
    """
    Structured result from a pytest run

    Attributes:
        passed: True iff pytest exit code == 0
        stdout: Full pytest stdout (useful for the Judge to see why a test failed)
        stderr: Full stderr (for syntax errors)
        timed_out: True if we hit time limit
    """

    passed: bool
    stdout: str
    stderr: str
    timed_out: bool


def run_test(
    target_code: str, test_code: str, *, image: str = "testforge-sandbox", timeout_seconds: int = 60
) -> ExecutorResult:
    """
    Run tests against some target code in docker sandbox

    Args:
        target_code: Full source of the target function
        test_code: Test generated by Author
        image: Docker image (default 'testforge-sandbox')
        timeout_seconds: timeout limit (default 60 seconds)

    Returns:
        List of mutated source strings
    """
    # create Docker environment to run tests in
    with tempfile.TemporaryDirectory() as d:
        Path(d, "target.py").write_text(target_code, encoding="utf-8")
        Path(d, "test_target.py").write_text(test_code, encoding="utf-8")
        try:
            # mount /work directory into a Docker container
            result = subprocess.run(
                ["docker", "run", "--rm", "-v", f"{d}:/work", "-w", "/work", image, "pytest", "-q"],
                capture_output=True,
                text=True,
                timeout=timeout_seconds,
            )
            return ExecutorResult(
                passed=result.returncode == 0,
                stdout=result.stdout,
                stderr=result.stderr,
                timed_out=False,
            )
        # timeout case
        except subprocess.TimeoutExpired as e:
            return ExecutorResult(
                passed=False,
                stdout=str(e.stdout) or "",
                stderr=str(e.stderr) or "",
                timed_out=True,
            )
