"""
Orchestrator
- Calls each agent in order

THE FLOW (one cycle)
1. Author writes a test for the target code
2. Executor runs Author's test on the original target
3. Adversary generates mutations
4. Executor runs the test against each mutation. Mutations the test FAILS on are "killed"
   and the rest are "survived".
5. If any mutations have survived and token limit not reached yet:
   Judge critiques the test and loop back to step 1, otherwise, return the result
6. Supervisor watches budgets the whole time and can break out of the loop if conditions are met
   (like token limit reached)
"""

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from .adversary import generate_mutations
from .author import author
from .executor import run_test
from .judge import judge
from .supervisor import Supervisor

TRACES_DIR = Path(__file__).resolve().parents[2] / "traces"


@dataclass
class CycleResult:
    """Final report from one orchestration cycle."""

    target_name: str
    test_code: str
    mutations_total: int
    mutations_killed: int
    kill_rate: float
    surviving_mutations: list[str]
    judge_critique: str | None
    stopped_reason: str | None
    tokens_used: int


def run_cycle(
    target_code: str,
    target_name: str,
    *,
    author_model: str = "openai/gpt-oss-120b:free",
    judge_model: str = "z-ai/glm-4.5-air:free",
) -> CycleResult:
    """
    Runs a full cycle on a single target function

    Args:
        target_code: The original function
        target_name: Name of function in target_code
        author_model: Author llm
        judge_model: Judge llm

    Returns:
        (critique_text, tokens_used)
    """

    supervisor = Supervisor()
    tokens_used = 0
    last_critique = None

    while True:
        # Author creates pytest for target code
        test_code, tokens = author(target_code, author_model, last_critique)
        tokens_used += tokens
        supervisor.record_tokens(tokens)

        # run test created by author
        result = run_test(target_code, test_code)
        if not result.passed:
            return CycleResult(
                target_name=target_name,
                test_code=test_code,
                mutations_total=0,
                mutations_killed=0,
                kill_rate=0.0,
                surviving_mutations=[],
                judge_critique=None,
                stopped_reason="initial_test_failed",
                tokens_used=tokens_used,
            )

        # Adversary generates mutations in target code
        mutations = generate_mutations(target_code)
        mutations_killed = 0
        surviving_mutations = []
        # run the original tests generated by Author on mutated target code
        for m in mutations:
            mut_result = run_test(m, test_code)
            if not mut_result.passed:
                mutations_killed += 1
            else:
                surviving_mutations.append(m)

        # see if the tests generated by author fail on mutated code
        kill_rate = mutations_killed / len(mutations) if mutations else 0.0

        trace = {
            "target_name": target_name,
            "test_code": test_code,
            "mutations_total": len(mutations),
            "mutations_killed": mutations_killed,
            "kill_rate": kill_rate,
            "tokens_used": tokens_used,
        }
        # write result trace to log
        write_trace(target_name, trace)

        # break out of loop if Supervisor gives reason to
        stop = supervisor.should_stop()
        if not surviving_mutations or stop:
            stopped_reason = stop
            break

        # Judge provides feedback on the test case that passed on mutation
        critique, c_tokens = judge(target_code, test_code, surviving_mutations, judge_model)
        supervisor.record_tokens(c_tokens)
        supervisor.record_retry()
        tokens_used += c_tokens
        last_critique = critique

    return CycleResult(
        target_name=target_name,
        test_code=test_code,
        mutations_total=len(mutations),
        mutations_killed=mutations_killed,
        kill_rate=kill_rate,
        surviving_mutations=surviving_mutations,
        judge_critique=last_critique,
        stopped_reason=stopped_reason,
        tokens_used=tokens_used,
    )


# writes a trace log (useful for debugging)
def write_trace(target_name: str, trace: dict[str, Any]) -> None:
    """
    Append-only trace log (aka a compliance audit trail)

    Args:
        target_name: Name of function in target_code
        trace: log

    Returns:
        None
    """
    # create /traces directory
    TRACES_DIR.mkdir(exist_ok=True)
    path = TRACES_DIR / f"{target_name}.jsonl"
    with path.open("a") as f:
        f.write(json.dumps(trace, default=str) + "\n")
